version: "3.2"

services:
  postgraphql:
    image: postgraphql/postgraphql:latest
    ports:
      - "5000"
    environment:
      PGUSER: kodiaq
      PGPASSWORD: kodiaq
      PGHOST: postgres
      PGDATABASE: kodiaq_development
      PGPORT: 5432
    links:
      - postgres

  postgres:
    image: 'science_db_postgres:latest'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: 
