version: "3.2"

services:
  science_db_psql:
    build:
      context: .
      dockerfile: science_db_psql.txt
    links:
      - postgres

  postgres:
    build:
      context: ../ScienceDbBackend/
      dockerfile: postgres_db.txt
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
