version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: alpine_science_db.txt
    working_dir: /home/node/app
    links:
      - postgres
    ports:
      - "2939:22"
      - "3333:3333"
      - "3000:3000"
    volumes:
      - ..:/home/node/app

  postgres:
    build:
      context: .
      dockerfile: postgres_db.txt
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

volumes:
  data: {}
