version: "3.2"

services:
  postgres:
    build:
      context: ../ScienceDbBackend/
      dockerfile: postgres_db.txt
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

  science_db_backend:
    build:
      context: ../ScienceDbBackend/
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - /home/hallab/projects/ReconstructDb/ScienceDbBackend:/usr/src/app
    command: 'npm start'
    #labels:
    #  traefik.enable: "true"
    #  traefik.backend: "science_db_backend"
    #  traefik.frontend.rule: "Host:vmd17974.hallab.de,vmd17974.contabo.host;PathPrefix:/reconstructdb_backend"
    #  traefik.frontend.auth.basic: "testuser:$$apr1$$oQPKJJuG$$GLUGkFH1WkLN.D68SoXJQ."
    #  traefik.docker.network: "reverseproxy"
    #  traefik.port: "3000"
    networks:
      - reverseproxy
      - backend

  science_db_gui:
    build:
      context: ../ScienceDbGui/
      dockerfile: Dockerfile
    environment:
      PORT: 3333
    ports:
      - "3333:3333"
    volumes:
      - /home/hallab/projects/ReconstructDb/ScienceDbGui:/usr/src/app
    command: "npm run dev"
    # labels:
    #   traefik.enable: "true"
    #   traefik.backend: "science_db_gui"
    #   traefik.frontend.rule: "Host:vmd17974.hallab.de,vmd17974.contabo.host"
    #   #traefik.frontend.rule: "Host:vmd17974.contabo.host;PathPrefix:/science_db_gui"
    #   traefik.frontend.auth.basic: "testuser:$$apr1$$oQPKJJuG$$GLUGkFH1WkLN.D68SoXJQ."
    #   traefik.docker.network: "reverseproxy"
    #   traefik.port: "3333"
    networks:
      - reverseproxy
      - backend

  postgraphql:
    image: postgraphql/postgraphql:v3
    #    ports:
    #      - "5000:5000"
    environment:
      PGUSER: kodiaq
      PGPASSWORD: kodiaq
      PGHOST: postgres
      PGDATABASE: kodiaq_development
      PGPORT: 5432
    labels:
      traefik.enable: "true"
      traefik.backend: "postgraphql"
      traefik.frontend.rule: "Host:vmd17974.hallab.de,vmd17974.contabo.host;PathPrefix:/reconstructdb_graphql"
      traefik.frontend.auth.basic: "testuser:$$apr1$$oQPKJJuG$$GLUGkFH1WkLN.D68SoXJQ."
      traefik.docker.network: "reverseproxy"
      traefik.port: "5000"
    networks:
      - reverseproxy
      - backend

volumes:
  data: 
networks:
  reverseproxy:
  # external: true
  backend:
