version: "3.2"

services:
  science_db_psql:
    image: 'science_db_postgres:latest'
    links:
      - postgres

  postgres:
    image: 'science_db_postgres:latest'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
