version: "3.2"

services:
  science_db_psql:
    build:
      context: .
      dockerfile: science_db_psql.txt
    networks:
      - backend

  postgres:
    build:
      context: ../ScienceDbBackend/
      dockerfile: postgres_db.txt
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  data: {}
