version: "3.2"

services:
  science_db_backend:
    image: 'science_db_backend:latest'
    links:
      - postgres
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    command: 'npm start'

  science_db_gui:
    image: 'science_db_gui:latest'
    links:
      - science_db_backend
    environment:
      PORT: 3333
    ports:
      - "3333:3333"
    command: 'npm run dev'

  postgres:
    image: 'science_db_postgres:latest'
    volumes:
      - data:/var/lib/postgresql/data

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth

volumes:
  data: {}
